### ISSUE TITLE
Missing on Packagist

### ISSUE THREAD

**Issue by simPod** [thephpleague/flysystem-sftp-v3#1]
Hi, this library is missing on packagist https://packagist.org/?query=flysystem%20sftp Mind adding it? Thanks!

**Comment by smknstd** [comment]
It seems it has been added early june: https://packagist.org/packages/league/flysystem-sftp-v3

**Comment by simPod** [comment]
Hmm, I see. Maybe it is not included in search when there's no release yet. 🤔 thanks
