### ISSUE TITLE
Connection closed prematurely

### ISSUE THREAD

**Issue by ikudosi** [thephpleague/flysystem-sftp-v3#4]
PHP: 8.1
PHPSECLIB: 3.0.14

I am using league/flysystem-sftp-v3 within Laravel and under the hood it uses this library. In regards to application usage, I am heavily doing SFTP transfers via queued jobs. I thought upgrading to latest phpseclib would resolve this issue as it's been going on for quite sometime, but it seems like it's still happening on my end. Below is the trace stack. So far, the only thing that's been saving my butt has been to ensure the job retries enough to make the transfer go through, but I would prefer not to rely on the retry mechanism. I've also opened duplicate ticket with phpseclib as I'm not sure if this their issue or within this package.

`phpseclib3\Exception\ConnectionClosedException: Connection closed prematurely in /var/www/html/vendor/phpseclib/phpseclib/phpseclib/Net/SSH2.php:4170 Stack trace: #0 /var/www/html/vendor/phpseclib/phpseclib/phpseclib/Net/SSH2.php(3753): phpseclib3\Net\SSH2->send_binary_packet() #1 /var/www/html/vendor/phpseclib/phpseclib/phpseclib/Net/SSH2.php(3633): phpseclib3\Net\SSH2->filter() #2 /var/www/html/vendor/phpseclib/phpseclib/phpseclib/Net/SSH2.php(3755): phpseclib3\Net\SSH2->get_binary_packet() #3 /var/www/html/vendor/phpseclib/phpseclib/phpseclib/Net/SSH2.php(3633): phpseclib3\Net\SSH2->filter() #4 /var/www/html/vendor/phpseclib/phpseclib/phpseclib/Net/SSH2.php(3755): phpseclib3\Net\SSH2->get_binary_packet() #5 /var/www/html/vendor/phpseclib/phpseclib/phpseclib/Net/SSH2.php(3633): phpseclib3\Net\SSH2->filter() #6 /var/www/html/vendor/phpseclib/phpseclib/phpseclib/Net/SSH2.php(3755): phpseclib3\Net\SSH2->get_binary_packet() #7 /var/www/html/vendor/phpseclib/phpseclib/phpseclib/Net/SSH2.php(3633): phpseclib3\Net\SSH2->filter() #8 /var/www/html/vendor/phpseclib/phpseclib/phpseclib/Net/SSH2.php(3755): phpseclib3\Net\SSH2->get_binary_packet() #9 /var/www/html/vendor/phpseclib/phpseclib/phpseclib/Net/SSH2.php(3633): phpseclib3\Net\SSH2->filter() #10 /var/www/html/vendor/phpseclib/phpseclib/phpseclib/Net/SSH2.php(3966): phpseclib3\Net\SSH2->get_binary_packet() #11 /var/www/html/vendor/phpseclib/phpseclib/phpseclib/Net/SFTP.php(3356): phpseclib3\Net\SSH2->get_channel_packet() #12 /var/www/html/vendor/phpseclib/phpseclib/phpseclib/Net/SFTP.php(1497): phpseclib3\Net\SFTP->get_sftp_packet() #13 /var/www/html/vendor/phpseclib/phpseclib/phpseclib/Net/SFTP.php(1387): phpseclib3\Net\SFTP->stat_helper() #14 /var/www/html/vendor/phpseclib/phpseclib/phpseclib/Net/SFTP.php(2945): phpseclib3\Net\SFTP->stat() #15 /var/www/html/vendor/phpseclib/phpseclib/phpseclib/Net/SFTP.php(2900): phpseclib3\Net\SFTP->get_xstat_cache_prop() #16 /var/www/html/vendor/phpseclib/phpseclib/phpseclib/Net/SFTP.php(2675): phpseclib3\Net\SFTP->get_stat_cache_prop() #17 /var/www/html/vendor/league/flysystem-sftp-v3/SftpAdapter.php(128): phpseclib3\Net\SFTP->is_dir() #18 /var/www/html/vendor/league/flysystem-sftp-v3/SftpAdapter.php(120): League\Flysystem\PhpseclibV3\SftpAdapter->makeDirectory() #19 /var/www/html/vendor/league/flysystem-sftp-v3/SftpAdapter.php(97): League\Flysystem\PhpseclibV3\SftpAdapter->ensureParentDirectoryExists() #20 /var/www/html/vendor/league/flysystem-sftp-v3/SftpAdapter.php(144): League\Flysystem\PhpseclibV3\SftpAdapter->upload() #21 /var/www/html/vendor/league/flysystem/src/Filesystem.php(56): League\Flysystem\PhpseclibV3\SftpAdapter->write() #22 /var/www/html/vendor/laravel/framework/src/Illuminate/Filesystem/FilesystemAdapter.php(357): League\Flysystem\Filesystem->write() #23 /var/www/html/app/Jobs/StoreContentToDisk.php(37): Illuminate\Filesystem\FilesystemAdapter->put() #24 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(36): App\Jobs\StoreContentToDisk->handle() #25 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Util.php(41): Illuminate\Container\BoundMethod::Illuminate\Container\{closure}() #26 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(93): Illuminate\Container\Util::unwrapIfClosure() #27 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(37): Illuminate\Container\BoundMethod::callBoundMethod() #28 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Container.php(651): Illuminate\Container\BoundMethod::call() #29 /var/www/html/vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php(128): Illuminate\Container\Container->call() #30 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(141): Illuminate\Bus\Dispatcher->Illuminate\Bus\{closure}() #31 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(116): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}() #32 /var/www/html/vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php(132): Illuminate\Pipeline\Pipeline->then() #33 /var/www/html/vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php(98): Illuminate\Bus\Dispatcher->dispatchNow() #34 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Bus/Dispatchable.php(57): Illuminate\Bus\Dispatcher->dispatchSync() #35 /var/www/html/app/LTB/OrderIntegration/OrderApiHandler.php(86): App\Jobs\StoreContentToDisk::dispatchSync() #36 /var/www/html/app/Services/Dropship/Dropship.php(443): App\LTB\OrderIntegration\OrderApiHandler->sendViaSFTP() #37 /var/www/html/app/Jobs/SendDropshipOrderToAx.php(71): App\Services\Dropship\Dropship->sendOrderToAx() #38 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(36): App\Jobs\SendDropshipOrderToAx->handle() #39 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Util.php(41): Illuminate\Container\BoundMethod::Illuminate\Container\{closure}() #40 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(93): Illuminate\Container\Util::unwrapIfClosure() #41 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(37): Illuminate\Container\BoundMethod::callBoundMethod() #42 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Container.php(651): Illuminate\Container\BoundMethod::call() #43 /var/www/html/vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php(128): Illuminate\Container\Container->call() #44 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(141): Illuminate\Bus\Dispatcher->Illuminate\Bus\{closure}() #45 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(116): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}() #46 /var/www/html/vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php(132): Illuminate\Pipeline\Pipeline->then() #47 /var/www/html/vendor/laravel/framework/src/Illuminate/Queue/CallQueuedHandler.php(123): Illuminate\Bus\Dispatcher->dispatchNow() #48 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(141): Illuminate\Queue\CallQueuedHandler->Illuminate\Queue\{closure}() #49 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(116): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}() #50 /var/www/html/vendor/laravel/framework/src/Illuminate/Queue/CallQueuedHandler.php(125): Illuminate\Pipeline\Pipeline->then() #51 /var/www/html/vendor/laravel/framework/src/Illuminate/Queue/CallQueuedHandler.php(69): Illuminate\Queue\CallQueuedHandler->dispatchThroughMiddleware() #52 /var/www/html/vendor/laravel/framework/src/Illuminate/Queue/Jobs/Job.php(98): Illuminate\Queue\CallQueuedHandler->call() #53 /var/www/html/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(429): Illuminate\Queue\Jobs\Job->fire() #54 /var/www/html/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(379): Illuminate\Queue\Worker->process() #55 /var/www/html/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(173): Illuminate\Queue\Worker->runJob() #56 /var/www/html/vendor/laravel/framework/src/Illuminate/Queue/Console/WorkCommand.php(150): Illuminate\Queue\Worker->daemon() #57 /var/www/html/vendor/laravel/framework/src/Illuminate/Queue/Console/WorkCommand.php(134): Illuminate\Queue\Console\WorkCommand->runWorker() #58 /var/www/html/vendor/laravel/horizon/src/Console/WorkCommand.php(51): Illuminate\Queue\Console\WorkCommand->handle() #59 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(36): Laravel\Horizon\Console\WorkCommand->handle() #60 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Util.php(41): Illuminate\Container\BoundMethod::Illuminate\Container\{closure}() #61 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(93): Illuminate\Container\Util::unwrapIfClosure() #62 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(37): Illuminate\Container\BoundMethod::callBoundMethod() #63 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Container.php(651): Illuminate\Container\BoundMethod::call()...`

**Comment by kiropowered** [comment]
Hello @ikudosi,
I also experience this issue with the latest version.
So far I mitigate the issue the same as you do, when it fails I queue the task again and then it works. 
So it's a little bit ugly, did you find a clean solution ?

**Comment by ikudosi** [comment]
I just said screw it and switched over to S3. The thing I was connecting to was our company's AWS Family Transfer which I think does some interesting SFTP connection, however, the end medium is still S3. I have a feeling the issue I had isn't really package related but more of AWS?
